### ISSUE TITLE
randon peers

### ISSUE THREAD

**Issue by thiago-tsnnst** [kunoada/Cardano#1]
hi, just a tip

when creating a new list of peers, if the 2 first peers in the old file will be the same on the next file generated after checking the list peers, would be nice remove this 2 from the start of the new file and put them in the end

the problem is, the 30 minutes quarantine to bootstrap

**Comment by kunoada** [comment]
Hi @thiago-tsnnst 

Thank you for your feedback!

As far as I'm concerned, jormungandr will pick a random peer from the list (this is at least how I see it when looking in the logs). Therefore, I don't think this should be necessary. Please correct me if I'm wrong.

**Comment by thiago-tsnnst** [comment]
Humm, interesting, i observe that it tends to pick the first in the list

**Comment by kunoada** [comment]
I've asked the community how their experience is when starting jormungandr, and it seems like more has observed jormungandr choose a random peer from the list.

Should we close this issue?

**Comment by thiago-tsnnst** [comment]
Yes, lets close
